### PR TITLE
Fix Documentation for imhist and histeq. Fixes #510

### LINKED ISSUE #510: Documentation doesnt build for imhist and histeq
The docstring should be before the function definition.

### PR DESCRIPTION
**Pull request by mronian**

### CODE REVIEW

File: src/algorithms.jl [hunk 1]
```diff
@@ -1318,6 +1294,28 @@ end
 
 histeq{T<:Gray, D<:Union{U8, U16}}(img::AbstractArray{T}, nbins, dtype::Type{D} = U8) = histeq(_prep_image_for_histeq(img, dtype), nbins, ColorVectorSpace.typemin(Gray{dtype}), ColorVectorSpace.typemax(Gray{dtype}))
 
+"""
+```
+hist_equalised_img = histeq(img, nbins, dtype = "8bit")
```
Comment (timholy) [inline src/algorithms.jl]: Is a string still supported?

**Comment by timholy** [comment]
Not sure I quite understand what changed (functionally) here, other than moving code around.

**Comment by timholy** [comment]
Oh, sorry, I just read #510.
