### PR TITLE
Fixes Issues with Histeq, changes the dtype argument.

### LINKED ISSUE #502: Return type of Histeq is always Float, should be the one supplied.
Need to convert before returning.

### LINKED ISSUE #503: Line 1272/1274, algorithms.jl gives type of Array{Any} leading to garbage Image while saving
Need to use ```convert(Array{Colors.base_colorant_type(eltype(img)){dtype}}, img)```

### PR DESCRIPTION
**Pull request by mronian**
- Changed dtype argument
- Fixed #503 
- Fixed #502 

Some unsolved issues : 

- #504 
- #503 (The convert(Array{GrayA}, img) method is not working. The returned datatype for transaparent images is ```Array{Any}``` instead of ```Array{Gray}```. This causes an error while saving the image.)

```julia
julia> img = testimage("house")
GrayA Images.Image with:
  data: 512×512 Array{ColorTypes.GrayA{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> h=Images.histeq(img, 1000)
Gray Images.Image with:
  data: 512×512 Array{Any,2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> save("test.jpg", h)
WARNING: MethodError(ImageMagick.mapinfo,(
Gray Images.Image with:
  data: 512×512 Array{Any,2}
  properties:
    colorspace: Gray
    spatialorder:  x y,))
 in save_ at /home/jarvis/.julia/v0.5/ImageMagick/src/ImageMagick.jl:158 [inlined] (repeats 2 times)
 in #save#5(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/ImageMagick/src/ImageMagick.jl:68
 in save(::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/ImageMagick/src/ImageMagick.jl:68
 in #save#18(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:95
 in save(::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:89
 in #save#14(::Array{Any,1}, ::Function, ::String, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:51
 in save(::String, ::Images.Image{Any,2,Array{Any,2}}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:51
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
ERROR: MethodError: no method matching mapinfo(::Images.Image{Any,2,Array{Any,2}})
 in save_ at /home/jarvis/.julia/v0.5/ImageMagick/src/ImageMagick.jl:158 [inlined] (repeats 2 times)
 in #save#5(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/ImageMagick/src/ImageMagick.jl:68
 in save(::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/ImageMagick/src/ImageMagick.jl:68
 in #save#18(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:95
 in save(::FileIO.File{FileIO.DataFormat{:JPEG}}, ::Images.Image{Any,2,Array{Any,2}}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:89
 in #save#14(::Array{Any,1}, ::Function, ::String, ::Images.Image{Any,2,Array{Any,2}}, ::Vararg{Images.Image{Any,2,Array{Any,2}},N}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:51
 in save(::String, ::Images.Image{Any,2,Array{Any,2}}) at /home/jarvis/.julia/v0.5/FileIO/src/loadsave.jl:51
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

```

### CODE REVIEW

**Comment by mronian** [comment]
The test is failing due to ```ERROR: LoadError: LoadError: UndefVarError: U16 not defined```. Doesn't it use the latest version of Colors automatically?

**Comment by timholy** [comment]
Travis will use the latest *tagged* version of packages by default. We can tag a new release. Anything else you know of that needs to be changed in ColorTypes before we do so?

Also, FYI as a temporary measure you can change [the test script](https://github.com/timholy/Images.jl/blob/06eca29a0cf2b18e141e000f5a992f2a4c64b566/.travis.yml#L12-L13) to check out the master version of a package. But it's important to not forget to change it back! So in general the best approach is to tag a new version of whatever package needs to be bumped.

Finally, please do add some tests---I won't merge this without them :wink:. Test would have likely caught the problem originally. As a tip, I often try to write the tests *before* I write the code to implement the functionality; it really helps clarify one's thinking about what the API should look like.

**Comment by mronian** [comment]
Completely agree. Will add tests to this PR :)

Regarding ColorTypes, I can't think of anything right now. I can change the test script for a few days before a new release is tagged so that any new changes can be included in that too.

File: src/algorithms.jl [hunk 1]
```diff
@@ -1332,6 +1326,7 @@ function histeq{T<:Union{Gray,Number}}(img::AbstractArray{T}, nbins::Int, minval
     hist_equalised_img = [max(1,Int(ceil((x-minval)*cdf_length/(maxval-minval)))) for x in img]
     hist_equalised_img = [minval + ((cdf[x]-cdf[1])*(maxval-minval)/(cdf[end]-cdf[1])) for x in hist_equalised_img]
```
Comment (timholy) [inline src/algorithms.jl]: If you still need it, much better to put `T` in front of the comprehension, `T[minval + ...]`. Your `convert` line below could end up creating yet another temporary, and that's not necessary.

But it looks like you probably have another type-instability here: `hist_equalize_img` is being defined twice and it might have different types each time. The trivial fix is to use two different names for these variables.

Comment (timholy) [inline src/algorithms.jl]: In other words, you shouldn't have to put `T` in front of a comprehension unless you are explicitly converting to that type.

One last point (sorry for sounding like a broken record): this function needs to compute the `histogram` and `cdf` temporaries---those are fine. But everything that comes afterwards is a "scalar operation," i.e., each pixel is processed independently of the rest. It might be best to define a `histeq_rescale` function that achieves the calculations on [these lines](https://github.com/timholy/Images.jl/blob/06eca29a0cf2b18e141e000f5a992f2a4c64b566/src/algorithms.jl#L1332-L1333) for a single pixel. Then you just say
```jl
hist_equalised_img = [histeq_rescale(x, cdf, minval, maxval) for x in img]
```
The reason this matters: each time you loop over the pixels in an image, you make it slower due to the movement of memory to and from the CPU. Best to do as much work as possible in a single pass through the image.

**Comment by timholy** [comment]
I'll go ahead and submit a PR for a new release right now.

**Comment by timholy** [comment]
OK, it's merged, so any new pushes will be tested with the new ColorTypes.

**Comment by timholy** [comment]
This is a good step forward, so I'll merge. We can polish further later.
